job_environments:
  common_environment: &common_environment
    CONTAINER_PREFIX: planet4-colombia
    APP_HOSTPATH: colombia
    WP_DB_NAME_PREFIX: planet4-colombia_wordpress
  develop_environment: &develop_environment
    APP_ENVIRONMENT: development
    APP_HOSTNAME: www-dev.greenpeace.org
    CLOUDSQL_INSTANCE: p4-develop-k8s
    GOOGLE_PROJECT_ID: planet-4-151612
    GCLOUD_CLUSTER: p4-development
    HELM_NAMESPACE: develop
    HELM_RELEASE: planet4-colombia
    NEWRELIC_APPNAME: P4 Colombia Development
    WP_DB_NAME: planet4-colombia_wordpress_develop
    WP_STATELESS_BUCKET: planet4-colombia-stateless-develop
  release_build_env: &release_build_env
    GOOGLE_PROJECT_ID: planet4-production
  release_environment: &release_environment
    APP_ENVIRONMENT: staging
    APP_HOSTNAME: www-stage.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: colombia
    HELM_RELEASE: planet4-colombia-release
    NEWRELIC_APPNAME: P4 Colombia Release
    WP_DB_NAME: planet4-colombia_wordpress_release
    WP_STATELESS_BUCKET: planet4-colombia-stateless-release
  production_environment: &production_environment
    APP_HOSTNAME: www.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: colombia
    HELM_RELEASE: planet4-colombia-master
    MIN_REPLICA_COUNT: 2
    NEWRELIC_APPNAME: P4 Colombia Production
    WP_DB_NAME: planet4-colombia_wordpress_master
    WP_STATELESS_BUCKET: planet4-colombia-stateless